### PR TITLE
Initial node w/ terraform

### PR DESCRIPTION
**Pull request by stbenjam**
Initial PR to handle the minimum requirements to replace 07-deploy-masters in metalkube.

Example `main.tf` is in the changes to README.md

### CODE REVIEW

**Comment by stbenjam** [comment]
This is in a state that can be reviewed.  It get go through the whole process implemented in `07_deploy_masters.sh` to deploy a master.  There is so much to clean up and figure out terraform's quirks. 

Here's what the .tf file should look like:
   https://github.com/metalkube/terraform-provider-ironic/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8

Here's terraform deploying a master (top window: watching `node list`, bottom window: terraform output)

terraform

**Comment by stbenjam** [comment]
(Note to test this, you'd need the ISO building tools which is still a WIP - https://github.com/gophercloud/utils/pull/82)

**Comment by markmc** [comment]
Awesome to see this progress

I did have some difficulties building this with your gophercloud/utils PR, what with go modules and all

This looks far enough along that we should be able to quickly have people start banging on it by using it in dev_scripts 07_deploy_masters.sh. I pushed a WIP hack towards this as metalkube/dev-scripts#135 - please take a look

**Comment by markmc** [comment]
Go home golang, you're ... tired!

```
$ git diff  c681981..a72bf0b | diffstat
 8582 files changed, 1551796 insertions(+), 478085 deletions(-)
$ find vendor | wc -l
1871
```

Still ... it builds without hacks. Perhaps that's most important right now. We can evaluate the dependency and vendoring approach easily later?

**Comment by stbenjam** [comment]
Yup, sounds good to me.

**Comment by hardys** [comment]
Good to see this merge, nice work!  Next time we should probably squash the commits though, some of the intermediate commit messages are, uh, terse ;)

**Comment by stbenjam** [comment]
@hardys `Asdf` isn't descriptive? :smile: Sorry, if you want I could squash merge `master` and force push before anyone starts using this

**Comment by hardys** [comment]
> @hardys `Asdf` isn't descriptive? smile Sorry, if you want I could squash merge `master` and force push before anyone starts using this

I'm not too worried, just thought it worth mentioning for future PRs :)

**Pull request merged**
